name: Test

on:
  pull_request:
    branches:
      - bugfix/*
      - feature/*
      - hotfix/*
      - dev*
      - master*
      - release/*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.5'

      - name: Run tests
        run: go test -v ./tests/* --failfast
